"""Does the damage evolution actually degrade the stiffness on a solid element?

The preprocessor accepts `*Damage Evolution` next to the general stress-based criteria
for anisotropic materials, and those criteria do take solid elements. That is not enough
to conclude that a solid element can carry damage: the keyword's own documentation lists
where the evolution applies, and an elastic anisotropic material is not on the list (the
list covers cohesive elements, plane-stress elements with the fibre-reinforced damage
model, and, in Explicit, elastic-plastic materials). An input file that is accepted but
whose evolution is ignored would leave the material elastic and silently report nothing
but a failure index, which is exactly the kind of quiet failure this project's checks
exist to catch.

Each case is a single element pulled along the fibre direction by a prescribed
displacement, ramped to about three times the fibre tensile failure strain over a time
far longer than the wave transit. Two numbers decide it:

  * if the evolution is honoured, the reaction force peaks near the initiation strain and
    then falls, so final/peak is well below one;
  * if it is ignored, the material stays elastic and the reaction rises with the
    displacement, so the final value *is* the peak and final/peak is one.

The SC8R case with Hashin is the control: that combination is documented to work, so it
must soften. Without the control a flat result could mean the test is wrong rather than
the model.

Run:  python check_damage_degradation.py
"""
import re
import subprocess
import sys
from pathlib import Path

from capability_sweep import (ABAQUS, G_FIBRE_T, MAX_STRAIN_LIMITS, MAX_STRESS_LIMITS,
                              TSAIWU_COEFFICIENTS, block)

HERE = Path(__file__).resolve().parent
RUNS = HERE / 'runs' / 'degradation'

NODES = """*Node
1, 0., 0., 0.
2, 1e-3, 0., 0.
3, 1e-3, 1e-3, 0.
4, 0., 1e-3, 0.
5, 0., 0., 5e-4
6, 1e-3, 0., 5e-4
7, 1e-3, 1e-3, 5e-4
8, 0., 1e-3, 5e-4
*Nset, nset=BOT
1, 2, 3, 4
*Nset, nset=TOP
5, 6, 7, 8
"""

STEP = """*Step, name=S1, nlgeom=NO
*Dynamic, Explicit
, 2e-4
*Boundary, amplitude=RAMP
TOP, 1, 1, 3e-5
*Boundary
BOT, ENCASTRE
*Output, history
*Node Output, nset=TOP
RF1
*Output, field, frequency=20
*Element Output
SDEG
*End Step
"""

AMPLITUDE = """*Amplitude, name=RAMP
0., 0., 2e-4, 1.
"""

CASES = {
    # The two solid cases that matter, plus a principal-value one for contrast.
    'deg_c3d8_max_stress': ('C3D8', 'solid', block('MAX STRESS', MAX_STRESS_LIMITS)),
    'deg_c3d8_maxps': ('C3D8', 'solid',
                       block('MAXPS', MAX_STRESS_LIMITS.split(',')[0])),
    'deg_c3d8_quads': ('C3D8', 'solid',
                       block('QUADS', '1.5e9, 1.2e9, 5.0e7, 2.0e8, 7.0e7')),
    # Control: documented to degrade.
    'deg_sc8r_hashin': ('SC8R', 'shell',
                        block('HASHIN', '1.5e9, 1.2e9, 5.0e7, 2.0e8, 7.0e7, 7.0e7',
                              '9.16e4, 7.99e4, 2.2e2, 1.1e3')),
    # A solid with no damage at all: the reaction must track the displacement exactly,
    # which is what the elastic reference is.
    'deg_c3d8_elastic': ('C3D8', 'solid', ''),
}


def deck(element, kind, damage):
    if kind == 'shell':
        geometry = ('*Shell Section, elset=ALL, material=CFRP, orientation=Fibre\n'
                    '5.0e-4, 5')
    else:
        geometry = ('*Section Controls, name=SC, max degradation=1.0\n'
                    '*Solid Section, elset=ALL, material=CFRP, orientation=Fibre, '
                    'controls=SC\n,')
    damage_block = f'{damage}\n' if damage.strip() else ''
    return f"""*Heading
** degradation check, generated by check_damage_degradation.py
*Preprint, echo=NO, model=NO, history=NO, contact=NO
{NODES}*Element, type={element}
1, 1, 2, 3, 4, 5, 6, 7, 8
*Elset, elset=ALL
1,
*Orientation, name=Fibre
1., 0., 0., 0., 1., 0.
3, 0.
{geometry}
*Material, name=CFRP
*Density
1570.,
*Elastic, type=ENGINEERING CONSTANTS
1.281e11, 8.2e9, 8.2e9, 0.27, 0.27, 0.20, 4.7e9, 4.7e9
3.44e9,
{damage_block}{AMPLITUDE}{STEP}"""


def reaction_summary(odb):
    """Run the odb reader and pull out the reaction peak, the final value and the end
    time of the record, which together say whether the ramp actually got anywhere."""
    top_nodes = ','.join(str(label) for label in (5, 6, 7, 8))
    proc = subprocess.run([ABAQUS, 'python', str(HERE / 'read_odb_reaction.py'),
                           str(odb), 'RF1', top_nodes],
                          cwd=str(RUNS), capture_output=True, text=True, errors='replace')
    match = re.search(r'(\d+) samples, last at t=([\d.eE+-]+) s, peak ([\d.eE+-]+) at '
                      r't=([\d.eE+-]+) s, final ([\d.eE+-]+)', proc.stdout)
    if not match:
        print(proc.stdout)
        return None
    return dict(samples=int(match.group(1)), last_t=float(match.group(2)),
                peak=float(match.group(3)), peak_t=float(match.group(4)),
                final=float(match.group(5)))


def main():
    RUNS.mkdir(parents=True, exist_ok=True)
    print('prescribed displacement 3.0e-2 strain along the fibre direction.')
    print('final/peak near 1 means the material stayed elastic; well below 1 means the')
    print('stiffness degraded after initiation.\n')
    print('%-22s %-6s %10s %11s %10s %11s %10s'
          % ('case', 'elem', 'last t [s]', 'peak RF1 [N]', 'peak t [s]', 'final RF1 [N]',
             'final/peak'))
    verdicts = {}
    step_end = 2e-4
    for name, (element, kind, damage) in CASES.items():
        (RUNS / f'{name}.inp').write_text(deck(element, kind, damage), encoding='ascii')
        subprocess.run([ABAQUS, f'job={name}', f'input={name}.inp', 'interactive'],
                       cwd=str(RUNS), capture_output=True, text=True, errors='replace')
        odb = RUNS / f'{name}.odb'
        if not odb.exists():
            print('%-22s %-6s  NO ODB' % (name, element))
            verdicts[name] = 'no odb'
            continue
        info = reaction_summary(odb)
        if info is None:
            verdicts[name] = 'no rf1'
            continue
        ratio = info['final'] / info['peak'] if info['peak'] else float('nan')
        # A record that stops short of the step end says nothing about softening: the
        # reaction is still rising because the ramp is still rising.
        complete = info['last_t'] >= 0.999 * step_end
        verdicts[name] = ('ramp incomplete' if not complete
                          else 'elastic (no degradation)' if ratio > 0.98
                          else 'degrades')
        print('%-22s %-6s %10.3g %11.4g %10.3g %11.4g %10.3f'
              % (name, element, info['last_t'], info['peak'], info['peak_t'], info['final'],
                 ratio))
    print()
    for name, verdict in verdicts.items():
        print('%-22s %s' % (name, verdict))
    return 0


if __name__ == '__main__':
    sys.exit(main())
